name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Make build script executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./scripts/build.sh

      - name: Build & Test (Unix)
        if: runner.os != 'Windows'
        run: |
          ./scripts/build.sh debug

      - name: Build & Test (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          scripts\build.bat debug-vs
