name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Define VCPKG_ROOT (Unix)
        if: runner.os != 'Windows'
        run: echo "VCPKG_ROOT=${{ runner.temp }}/vcpkg" >> $GITHUB_ENV

      - name: Define VCPKG_ROOT (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo VCPKG_ROOT=%RUNNER_TEMP%\vcpkg>>%GITHUB_ENV%

      - name: Bootstrap vcpkg (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg "$VCPKG_ROOT"
          "$VCPKG_ROOT"/bootstrap-vcpkg.sh -disableMetrics

      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg %VCPKG_ROOT%
          %VCPKG_ROOT%\bootstrap-vcpkg.bat -disableMetrics

      - name: Cache vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.temp }}/vcpkg/installed
            ${{ runner.temp }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json', '**/vcpkg-lock.json') }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Make build script executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./scripts/build.sh

      - name: Build & Test (Unix with vcpkg)
        if: runner.os != 'Windows'
        run: |
          # Use vcpkg-aware preset so dependencies resolve from vcpkg manifest
          ./scripts/build.sh debug-vcpkg

      - name: Build & Test (Windows with vcpkg)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          scripts\build.bat debug-vs-vcpkg
